### ISSUE TITLE
Add a New Project Section to the Portfolio Website

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/Portfolio#4]
The current portfolio website showcases several skills and projects, but it is missing a dedicated section for showcasing user testimonials. Adding a testimonials section will enhance the website's credibility and provide insights into the experiences of those who have interacted with the projects.

Acceptance Criteria:
1. Design: Create a visually appealing section titled "Testimonials" below the Projects section.
2. Content: Include at least three testimonials with the following information:
  a)User's name
  b)User's role (optional)
  c)The testimonial text
3. Responsive Design: Ensure the section is mobile-friendly and maintains readability across devices.
4. Interactivity: Implement hover effects to highlight testimonials on mouse-over.

Please assign this task to me under HacktoberFest 2024.

**Comment by Ayu-hack** [comment]
Assigned.
